apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-app

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: fitness-app

  template:
    metadata:
      labels:
        app: fitness-app

    spec:
      containers:
        - name: fitness-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          ports:
            - containerPort: 5000
