apiVersion: v1
kind: Service
metadata:
  name: fitness-service

spec:
  type: {{ .Values.service.type }}

  selector:
    app: fitness-app

  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
